apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.mysql.secret.type }}
data:
  {{- range $key, $value := .Values.redis.secret.keys }}
  {{ $key }}: {{ $value }}
  {{- end }}
