apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.auth.name }}
spec:
  type: {{ .Values.auth.svc.type }}
  selector:
    app: {{ .Values.auth.name }}
  ports:
    - name: {{ .Values.auth.name }}-svc-port
      port: {{ .Values.auth.svc.port }}
      targetPort: {{ .Values.auth.pod.port }}
      nodePort: {{ .Values.auth.svc.nodePort }}