apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.config.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.auth.name }}
data:
  {{- range $key, $value := .Values.mysql.config.keys }}
  {{ $key }}: "{{ $value }}"
  {{- end }}