apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.auth.name }}
spec:
  replicas: {{ .Values.auth.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.auth.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.name }}
    spec:
      containers:
        - name: {{ .Values.auth.name }}-pod
          image: {{ .Values.auth.pod.image }}:{{ .Values.auth.pod.tag }}
          ports:
            - containerPort: {{ .Values.auth.pod.port }}
          resources:
            requests:
              memory: {{ .Values.auth.pod.resources.requests.memory }}
              cpu: {{ .Values.auth.pod.resources.requests.cpu }}
            limits:
              memory: {{ .Values.auth.pod.resources.limits.memory }}
              cpu: {{ .Values.auth.pod.resources.limits.cpu }}
          env:
            {{- range $key, $value := .Values.mysql.config.keys }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.mysql.config.name }}
                  key: {{ $key }}
            {{- end }}
            {{- range $key, $value := .Values.mysql.secret.keys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.mysql.secret.name }}
                  key: {{ $key }}
            {{- end }}